# Generated by Django 3.0.5 on 2020-04-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=50, verbose_name='title in russian')),
                ('title_ky', models.CharField(max_length=50, verbose_name='title in kyrgyz')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location.Location')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
