# Generated by Django 3.0.5 on 2020-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type_ky',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type in kyrgyz'),
        ),
        migrations.AddField(
            model_name='location',
            name='type_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type in russian'),
        ),
    ]
