# Generated by Django 3.0.5 on 2020-04-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200416_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type_ky',
            field=models.CharField(default='type', max_length=50, verbose_name='type in kyrgyz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='type_ru',
            field=models.CharField(default='asdf', max_length=50, verbose_name='type in russian'),
            preserve_default=False,
        ),
    ]
