# Generated by Django 3.0.5 on 2020-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200416_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_ky',
            field=models.CharField(blank=True, default='Выберите', max_length=100, null=True, verbose_name='request in kyrgyz'),
        ),
        migrations.AlterField(
            model_name='location',
            name='request_ru',
            field=models.CharField(blank=True, default='Выберите', max_length=100, null=True, verbose_name='request in russian'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_ky',
            field=models.CharField(default='Местоположение', max_length=50, verbose_name='type in kyrgyz'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_ru',
            field=models.CharField(default='Местоположение', max_length=50, verbose_name='type in russian'),
        ),
    ]
