# Generated by Django 3.0.5 on 2020-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20200502_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='type_ky',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_ru',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('country', 'Страна'), ('region', 'Область'), ('city', 'Город'), ('district', 'Район'), ('pgt', 'ПГТ'), ('okmot', 'Айыл окмоту')], max_length=20, null=True, verbose_name='type'),
        ),
    ]
