# Generated by Django 3.0.5 on 2020-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20200502_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('country', 'Страна'), ('region', 'Область'), ('city', 'Город'), ('district', 'Район'), ('pgt', 'ПГТ'), ('', 'Айыл окмоту')], max_length=20, null=True, verbose_name='type'),
        ),
    ]
