# Generated by Django 3.0.5 on 2020-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20200502_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, default='41.668549', max_digits=9, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=6, default='74.961125', max_digits=9, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('country', 'Страна'), ('region', 'Область'), ('city', 'Город'), ('district', 'Район'), ('pgt', 'ПГТ'), ('okmot', 'Айыл окмоту')], default='country', max_length=20, verbose_name='type'),
        ),
    ]
