# Generated by Django 3.0.5 on 2020-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200503_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('country', 'Страна'), ('region', 'Область'), ('city', 'Город'), ('district', 'Район'), ('pgt', 'ПГТ'), ('aimak', 'Айылный аймак')], default='country', max_length=20, verbose_name='type'),
        ),
    ]
