# Generated by Django 3.0.6 on 2020-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20200506_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
