# Generated by Django 3.1.3 on 2021-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20200507_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='region'),
        ),
    ]
