# Generated by Django 3.0.5 on 2020-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200401_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='firebase cloud messaging id'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile', verbose_name='photo'),
        ),
    ]
