# Generated by Django 3.0.5 on 2020-04-11 08:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_favorite'),
        ('users', '0004_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_profile_photo_to, verbose_name='photo'),
        ),
    ]
