# Generated by Django 3.0.5 on 2020-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200411_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='firebase cloud messaging id'),
        ),
    ]
