# Generated by Django 3.0.6 on 2020-06-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_in_method',
            field=models.CharField(choices=[('credentials', 'credentials'), ('socials', 'socials')], default='credentials', max_length=50, verbose_name='sign in method'),
        ),
    ]
