# Generated by Django 3.0.8 on 2020-08-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_sign_in_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last active date'),
        ),
    ]
