# Generated by Django 3.1.1 on 2020-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_delete_productlike'),
        ('users', '0012_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='product.Product'),
        ),
    ]
