# Generated by Django 3.1.1 on 2020-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_uid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='firebase user id'),
        ),
    ]
