# Generated by Django 3.1.2 on 2020-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20200514_1253'),
        ('users', '0015_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='category.Category'),
        ),
    ]
