# Generated by Django 3.1.3 on 2021-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='phone', max_length=50, verbose_name='sign_in_provider'),
        ),
    ]
