# Generated by Django 3.1.3 on 2021-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('success', 'success'), ('on_review', 'on_review')], default='not_requested', max_length=50, verbose_name='business request status'),
        ),
    ]
