# Generated by Django 3.1.3 on 2021-08-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210705_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
            ],
            options={
                'db_table': 'sms_code',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='request_status',
            field=models.CharField(choices=[('not_requested', 'not_requested'), ('accepted', 'accepted'), ('success', 'success'), ('on_review', 'on_review'), ('expired', 'expired')], default='not_requested', max_length=50, verbose_name='business request status'),
        ),
    ]
