# Generated by Django 3.1.3 on 2021-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210808_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, verbose_name='Balance'),
        ),
    ]
