# Generated by Django 3.1.3 on 2021-08-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210705_1142'),
        ('users', '0020_auto_20210809_1515'),
    ]

    operations = [
    ]
