# Generated by Django 3.1.3 on 2021-08-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210806_1237'),
        ('users', '0021_merge_20210809_1534'),
    ]

    operations = [
    ]
