# Generated by Django 3.0.5 on 2020-04-03 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS')], max_length=5, verbose_name='title')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='rate')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('seller_type', models.CharField(choices=[('owner', 'owner'), ('reseller', 'reseller')], max_length=20, verbose_name='seller type')),
                ('price_kgs', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='price in kgs')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price in usd')),
                ('state', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('blocked', 'blocked'), ('on_review', 'on review')], default='on_review', max_length=20, verbose_name='state')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('show_count', models.PositiveIntegerField(default=0, verbose_name='show count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.Category', verbose_name='category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.Currency', verbose_name='currency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='location.Location', verbose_name='location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/photo', verbose_name='photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.Product', verbose_name='product')),
            ],
            options={
                'db_table': 'product_photo',
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Option', verbose_name='option')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Parameter', verbose_name='parameter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='product.Product', verbose_name='product')),
            ],
            options={
                'db_table': 'product_parameter',
            },
        ),
        migrations.CreateModel(
            name='ProductContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='product.Product', verbose_name='product')),
            ],
            options={
                'db_table': 'product_contact',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
