# Generated by Django 3.0.5 on 2020-04-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200408_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
