# Generated by Django 3.0.5 on 2020-04-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_upvote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_type',
        ),
    ]
