# Generated by Django 3.0.5 on 2020-04-20 09:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS')], max_length=5, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to=product.models.photo_upload_to, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS')], max_length=5, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='rate'),
        ),
    ]
