# Generated by Django 3.0.5 on 2020-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_parameter_type'),
        ('product', '0007_auto_20200422_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparameter',
            name='response',
            field=models.TextField(null=True, verbose_name='response'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.Option', verbose_name='option'),
        ),
    ]
