# Generated by Django 3.0.5 on 2020-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200427_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
    ]
