# Generated by Django 3.0.5 on 2020-05-06 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_rate_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='product.Product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'product_claim',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
