# Generated by Django 3.0.5 on 2020-05-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200502_1705'),
        ('product', '0010_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Option', verbose_name='option'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Parameter', verbose_name='parameter'),
        ),
    ]
