# Generated by Django 3.0.6 on 2020-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200507_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='response',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='response'),
        ),
    ]
