# Generated by Django 3.0.6 on 2020-05-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200509_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-upvote_date',)},
        ),
    ]
