# Generated by Django 3.0.6 on 2020-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='rating'),
        ),
    ]
