# Generated by Django 3.0.6 on 2020-07-10 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=20, verbose_name='type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='product.Product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'product_like',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
