# Generated by Django 3.0.8 on 2020-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200710_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_disabled',
            field=models.BooleanField(default=True, verbose_name='rating disabled'),
        ),
    ]
