# Generated by Django 3.0.8 on 2020-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200820_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_count',
            field=models.PositiveIntegerField(default=0, verbose_name='call count'),
        ),
        migrations.AddField(
            model_name='product',
            name='message_count',
            field=models.PositiveIntegerField(default=0, verbose_name='message count'),
        ),
    ]
