# Generated by Django 3.0.8 on 2020-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200820_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='claim',
            field=models.TextField(blank=True, null=True, verbose_name='claim'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='claim_date',
            field=models.DateTimeField(null=True),
        ),
    ]
