# Generated by Django 3.1 on 2020-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200825_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='type',
            field=models.CharField(choices=[('like', 'like')], max_length=20, verbose_name='type'),
        ),
    ]
