# Generated by Django 3.1.1 on 2020-09-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200902_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
