# Generated by Django 3.1.3 on 2021-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_keyword_is_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_kgs',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount_price_kgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount_price_usd'),
        ),
    ]
