# Generated by Django 3.1.3 on 2021-07-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20210625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='discount_price_usd'),
        ),
    ]
