# Generated by Django 3.1.3 on 2021-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20210705_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='discount_price_kgs'),
        ),
    ]
