# Generated by Django 3.1.3 on 2021-07-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(blank=True, editable=False, null=True, verbose_name='Идентификатор платежа')),
                ('provider', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('replenishment', 'replenishment'), ('purchase', 'purchase'), ('refund', 'refund')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
