# Generated by Django 3.1.3 on 2021-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paybox_id',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='id платежа в системе Paybox'),
        ),
    ]
