# Generated by Django 3.1.3 on 2021-07-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210709_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('canceled', 'canceled'), ('not paid', 'not paid')], default='not paid', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('replenishment', 'replenishment'), ('purchase', 'purchase')], max_length=100),
        ),
    ]
