# Generated by Django 3.1.3 on 2021-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210808_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS')], default='KGS', max_length=10)),
            ],
            options={
                'db_table': 'replenishment_db',
            },
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.IntegerField(verbose_name='На сколько месяцев'),
        ),
    ]
