# Generated by Django 3.0.6 on 2020-07-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20200507_1852'),
        ('notification', '0003_notification_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='title in russian')),
                ('title_ky', models.CharField(max_length=200, verbose_name='title in kyrgyz')),
                ('message_ru', models.TextField(blank=True, null=True, verbose_name='message in russian')),
                ('message_ky', models.TextField(blank=True, null=True, verbose_name='message in kyrgyz')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'db_table': 'push_notification',
            },
        ),
    ]
