# Generated by Django 3.1.3 on 2021-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20210412_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='notified_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user_chunk',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
