# Generated by Django 3.1.3 on 2021-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20210427_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='interval in minutes'),
        ),
    ]
