# Generated by Django 3.1.3 on 2021-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20210830_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('activated', 'activated'), ('stared', 'stared'), ('blocked', 'blocked'), ('payment', 'payment')], max_length=200, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
