# Generated by Django 3.1.3 on 2021-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20210905_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='title_ky',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.AddField(
            model_name='notification',
            name='description_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
