# Generated by Django 3.1.3 on 2021-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20210924_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='business',
            field=models.CharField(choices=[('business', 'business'), ('regular_user', 'regular_user'), ('everyone', 'everyone')], max_length=50, verbose_name='selection'),
        ),
    ]
