# Generated by Django 3.1.3 on 2021-04-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'advertisement_type',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('image_link', models.ImageField(upload_to='ads/')),
                ('click_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.advertisementtype')),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
    ]
