# Generated by Django 3.0.5 on 2020-04-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='receiver',
            new_name='seller',
        ),
    ]
