# Generated by Django 3.0.5 on 2020-04-30 07:34

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200429_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=chat.models.photo_upload_to, verbose_name='photo')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chat.Chat')),
            ],
            options={
                'db_table': 'chat_photo',
            },
        ),
    ]
