# Generated by Django 3.0.5 on 2020-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=50, verbose_name='title in russian')),
                ('title_ky', models.CharField(max_length=50, verbose_name='title in kyrgyz')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icons', verbose_name='icon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=50, verbose_name='title in russian')),
                ('title_ky', models.CharField(max_length=50, verbose_name='title in kyrgyz')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='category.Category')),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=50, verbose_name='title in russian')),
                ('title_ky', models.CharField(max_length=50, verbose_name='title in kyrgyz')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='category.Parameter')),
            ],
            options={
                'db_table': 'option',
            },
        ),
    ]
