# Generated by Django 3.0.5 on 2020-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_parameter_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('select', 'select'), ('enter', 'enter')], default='select', max_length=50, verbose_name='type'),
        ),
    ]
