# Generated by Django 3.0.6 on 2020-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200507_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='parameter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
