# Generated by Django 3.1.3 on 2021-01-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20200514_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='large_icon',
            field=models.ImageField(blank=True, null=True, upload_to='category/icons', verbose_name='large icon'),
        ),
    ]
