# Generated by Django 3.1.3 on 2021-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_large_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_slug',
            field=models.CharField(max_length=50, null=True, verbose_name='slug'),
        ),
    ]
