# Generated by Django 3.1.3 on 2021-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_categoryfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_many',
            field=models.BooleanField(default=False, verbose_name='is many'),
        ),
    ]
