# Generated by Django 3.0.6 on 2020-07-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='business',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='banner'),
        ),
    ]
