# Generated by Django 3.0.6 on 2020-07-10 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_businessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
