# Generated by Django 3.0.6 on 2020-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200710_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='upvote_count',
            field=models.SmallIntegerField(default=2, verbose_name='auto upper count'),
        ),
    ]
