# Generated by Django 3.0.8 on 2020-08-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20200716_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='product_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='product limit'),
        ),
    ]
