# Generated by Django 3.0.8 on 2020-08-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20200514_1253'),
        ('business', '0008_business_product_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='category.Category'),
            preserve_default=False,
        ),
    ]
