# Generated by Django 3.0.8 on 2020-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_businessrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deactivation_message',
            field=models.TextField(blank=True, null=True, verbose_name='deactivation message'),
        ),
        migrations.AddField(
            model_name='business',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='request message'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
