# Generated by Django 3.0.8 on 2020-08-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20200828_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessRequest',
        ),
    ]
