
# Generated by Django 3.1.3 on 2020-11-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20200507_1852'),
        ('business', '0011_delete_businessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='business.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='location.location')),
            ],
            options={
                'db_table': 'business_branches',
            },
        ),
    ]
