# Generated by Django 3.1.3 on 2021-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20201202_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbranch',
            name='lat',
            field=models.DecimalField(decimal_places=6, default='41.668549', max_digits=9, verbose_name='latitude'),
        ),
    ]
