# Generated by Django 3.1.3 on 2021-06-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_keyword_is_search'),
        ('business', '0015_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stats_type', models.CharField(choices=[('view', 'view'), ('call', 'call'), ('message', 'message'), ('click', 'click')], max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'business_statistics',
            },
        ),
    ]
