# Generated by Django 3.1.3 on 2021-06-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20210625_1131'),
        ('business', '0016_businessstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='catalog_name')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_catalog', to='business.business', verbose_name='business')),
                ('product', models.ManyToManyField(related_name='catalog_product', to='product.Product', verbose_name='product')),
            ],
            options={
                'db_table': 'business_catalog',
            },
        ),
    ]
