# Generated by Django 3.1.3 on 2021-06-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_businesscatalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscatalog',
            old_name='product',
            new_name='products',
        ),
    ]
