# Generated by Django 3.1.3 on 2021-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20210625_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery',
            field=models.IntegerField(blank=True, null=True, verbose_name='delivery'),
        ),
    ]
