# Generated by Django 3.1.3 on 2021-09-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20210901_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_not_demo',
            field=models.BooleanField(default=False, verbose_name='id not demo'),
        ),
    ]
