# Generated by Django 3.1.3 on 2021-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20210922_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='denied business'),
        ),
    ]
