# Generated by Django 3.1.3 on 2021-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_business_denied'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'business_period',
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации'),
        ),
    ]
