# Generated by Django 3.0.8 on 2020-08-18 04:58

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(default='1.0.0', max_length=20, validators=[info.models.validate_version], verbose_name='app version')),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
